# Generated by Django 3.2.13 on 2022-04-19 01:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coldwave_downpour_drought_dust_earthquake_forestfire_gale_heatwave_snow_typhoon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
