# Generated by Django 4.0.4 on 2022-04-26 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mark_region_name_alter_mark_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='name',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='disaster_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.disastertag'),
        ),
    ]
