# Generated by Django 3.2.13 on 2022-04-19 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220419_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coldwave',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='downpour',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='drought',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='dust',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='earthquake',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='forestfire',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='gale',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='heatwave',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='snow',
            name='freq',
        ),
        # migrations.RemoveField(
        #     model_name='typhoon',
        #     name='freq',
        # ),
        migrations.AddField(
            model_name='coldwave',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mark'),
        ),
        migrations.AddField(
            model_name='downpour',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mark'),
        ),
        migrations.AddField(
            model_name='drought',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mark'),
        ),
        migrations.AddField(
            model_name='dust',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mark'),
        ),
        migrations.AddField(
            model_name='earthquake',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mark'),
        ),
        migrations.AddField(
            model_name='forestfire',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mark'),
        ),
        migrations.AddField(
            model_name='gale',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mark'),
        ),
        migrations.AddField(
            model_name='heatwave',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mark'),
        ),
        migrations.AddField(
            model_name='snow',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mark'),
        ),
        migrations.AddField(
            model_name='typhoon',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mark'),
        ),
    ]
