# Generated by Django 4.0.4 on 2022-04-19 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mark_location'),
        ('api', '0004_auto_20220419_1049'),
    ]

    operations = [
    ]
