# Generated by Django 4.0.4 on 2022-04-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20220419_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='typhoon',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='typhoon',
            name='text',
        ),
        migrations.AddField(
            model_name='typhoon',
            name='disaster_tag',
            field=models.ManyToManyField(blank=True, to='api.disastertag'),
        ),
    ]
