# Generated by Django 4.0.4 on 2022-04-19 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_disastertag_remove_typhoon_freq_remove_typhoon_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disaster_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disastertag')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mark')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='downpour',
            name='location',
        ),
        migrations.RemoveField(
            model_name='drought',
            name='location',
        ),
        migrations.RemoveField(
            model_name='dust',
            name='location',
        ),
        migrations.RemoveField(
            model_name='earthquake',
            name='location',
        ),
        migrations.RemoveField(
            model_name='forestfire',
            name='location',
        ),
        migrations.RemoveField(
            model_name='gale',
            name='location',
        ),
        migrations.RemoveField(
            model_name='heatwave',
            name='location',
        ),
        migrations.RemoveField(
            model_name='snow',
            name='location',
        ),
        migrations.RemoveField(
            model_name='typhoon',
            name='disaster_tag',
        ),
        migrations.RemoveField(
            model_name='typhoon',
            name='location',
        ),
        migrations.DeleteModel(
            name='Coldwave',
        ),
        migrations.DeleteModel(
            name='Downpour',
        ),
        migrations.DeleteModel(
            name='Drought',
        ),
        migrations.DeleteModel(
            name='Dust',
        ),
        migrations.DeleteModel(
            name='Earthquake',
        ),
        migrations.DeleteModel(
            name='Forestfire',
        ),
        migrations.DeleteModel(
            name='Gale',
        ),
        migrations.DeleteModel(
            name='Heatwave',
        ),
        migrations.DeleteModel(
            name='Snow',
        ),
        migrations.DeleteModel(
            name='Typhoon',
        ),
    ]
